[package]
name = "firelocal-js"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "2.12.2", features = ["napi4"] }
napi-derive = "2.12.2"
firelocal-core = { path = "../../firelocal-core" }
serde_json = "1.0"
